### PR TITLE
Profiles

### PR DESCRIPTION
**Pull request by ssauc**
updating to merge

### CODE REVIEW

**Comment by JheregJAB** [comment]
I noticed there is a database change associated with this pull request.

Did you have to update database schema? Or was this database update in error?

**Comment by ssauc** [comment]
No I didn't update the database schema. The update to the database must be an error.

**Comment by ssauc** [comment]
I did create a query where I do joins to create the profile for the user. Not sure if that would create it.

**Comment by ssauc** [comment]
within the controllers.

**Comment by JheregJAB** [comment]
I'm going to close this pull request. I've reverted your database to be inline with Development and opened a new pull request.

**Pull request closed without merging**
